twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - '@SonataMedia/Form/media_widgets.html.twig'

when@test:
    twig:
        strict_variables: true
